const font = {
  head1_b_22: {
    fontSize: "2.2rem",
    lineHeight: "auto",
    letterSpacing: "0px",
    fontWeight: "700",
    fontFamily: "DM Sans",
  },
  body1_b_18: {
    fontSize: "1.8rem",
    lineHeight: "auto",
    letterSpacing: "0px",
    fontWeight: "700",
    fontFamily: "DM Sans",
  },
  body2_b_16: {
    fontSize: "1.6rem",
    lineHeight: "auto",
    letterSpacing: "0px",
    fontWeight: "700",
    fontFamily: "DM Sans",
  },
  body3_m_16: {
    fontSize: "1.6rem",
    lineHeight: "auto",
    letterSpacing: "0px",
    fontWeight: "500",
    fontFamily: "DM Sans",
  },
  body4_r_16: {
    fontSize: "1.6rem",
    lineHeight: "auto",
    letterSpacing: "0px",
    fontWeight: "400",
    fontFamily: "DM Sans",
  },
  body5_m_14: {
    fontSize: "1.4rem",
    lineHeight: "auto",
    letterSpacing: "0px",
    fontWeight: "500",
    fontFamily: "DM Sans",
  },
  body6_m_12: {
    fontSize: "1.2rem",
    lineHeight: "auto",
    letterSpacing: "0px",
    fontWeight: "500",
    fontFamily: "DM Sans",
  },
  button2_sb_20: {
    fontSize: "2rem",
    lineHeight: "140%",
    letterSpacing: "-0.5px",
    fontWeight: "600",
    fontFamily: "Pretendard",
  },
  head2_sb_18: {
    fontSize: "1.8rem",
    lineHeight: "140%",
    letterSpacing: "-0.18px",
    fontWeight: "600",
    fontFamily: "Pretendard",
  },
  button1_sb_18: {
    fontSize: "1.8rem",
    lineHeight: "140%",
    letterSpacing: "-0.5px",
    fontWeight: "600",
    fontFamily: "Pretendard",
  },
  title1_sb_16: {
    fontSize: "1.6rem",
    lineHeight: "140%",
    letterSpacing: "-0.032px",
    fontWeight: "600",
    fontFamily: "Pretendard",
  },
  body7_m_16: {
    fontSize: "1.6rem",
    lineHeight: "140%",
    letterSpacing: "-0.16px",
    fontWeight: "500",
    fontFamily: "Pretendard",
  },
  caption1_m_12: {
    fontSize: "1.2rem",
    lineHeight: "auto",
    letterSpacing: "0px",
    fontWeight: "500",
    fontFamily: "Pretendard",
  },
  body8_m_14: {
    fontSize: "1.4rem",
    lineHeight: "auto",
    letterSpacing: "-0.21px",
    fontWeight: "500",
    fontFamily: "Pretendard",
  },
  body9_sb_14: {
    fontSize: "1.4rem",
    lineHeight: "auto",
    letterSpacing: "-0.28px",
    fontWeight: "600",
    fontFamily: "Pretendard",
  },
};

export default font;
